name: balanceo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.2.1
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.3.0
  google_fonts: ^8.1.0
  hugeicons: ^1.1.7
  injectable: ^2.5.1
  intl: ^0.20.2
  reactive_forms: ^17.0.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.13.0
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
